name: 01_IAMRoles

#permissions:
  #id-token: write # This is required for requesting the JWT
  #contents: read # This is required for actions/checkout
  #pull-requests: write # This is required to add comments to Pull Requests
  #deployments: write # This is required to deactivate deployments

on:
  workflow_dispatch: # manually invoke 
    
  #pull_request:  
  #  paths:
  #    - "**.tf*"
  #    - ".github/workflows/deploy.yml"
  #push:
  #  branches:
  #    - "main"
  #  paths:
  #    - "**.tf*"
  #    - ".github/workflows/deploy.yml"

jobs:
  plan_dev:  # job name
    if: github.ref == 'refs/heads/FeatureBranch' # is reference FeatureBranch?
    uses: tracman33/gitreusableworkflows/.github/workflows/aws_tf_plan.yml@FeatureBranch    # run this plan on this branch
    with:
      path: IAMRoles
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  deploy_dev:
    needs: plan_dev
    uses: tracman33/gitreusableworkflows/.github/workflows/aws_tf_apply.yml@FeatureBranch
    with: 
        path: IAMRoles
        tf_vars_file: dev.tfvars
        gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      